USE [master]
GO

/****** Object:  Database [SACH_ONLINE]    Script Date: 14/08/2024 1:38:02 CH ******/
CREATE DATABASE [SACH_ONLINE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SACH_ONLINE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SACH_ONLINE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SACH_ONLINE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SACH_ONLINE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SACH_ONLINE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SACH_ONLINE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET ARITHABORT OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SACH_ONLINE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SACH_ONLINE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SACH_ONLINE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SACH_ONLINE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET RECOVERY FULL 
GO

ALTER DATABASE [SACH_ONLINE] SET  MULTI_USER 
GO

ALTER DATABASE [SACH_ONLINE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SACH_ONLINE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SACH_ONLINE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SACH_ONLINE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SACH_ONLINE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SACH_ONLINE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SACH_ONLINE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SACH_ONLINE] SET  READ_WRITE 
GO


